# Generated by Django 6.0.5 on 2026-06-09 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('trade_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='order_id')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderinfo', verbose_name='order')),
            ],
            options={
                'verbose_name': 'payment_info',
                'verbose_name_plural': 'payment_info',
                'db_table': 'tb_payment',
            },
        ),
    ]
