# Generated by Django 6.0.5 on 2026-05-29 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('first_letter', models.CharField(max_length=1, verbose_name='Initial')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brand',
                'db_table': 'tb_brand',
            },
        ),
        migrations.CreateModel(
            name='GoodsChannelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('name', models.CharField(max_length=20, verbose_name='GoodsChannel')),
            ],
            options={
                'verbose_name': 'GoodsChannel',
                'verbose_name_plural': 'GoodsChannel',
                'db_table': 'tb_channel_group',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='goods.goodscategory', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'goods_category',
                'verbose_name_plural': 'goods_category',
                'db_table': 'tb_goods_category',
            },
        ),
        migrations.CreateModel(
            name='GoodsChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('url', models.CharField(max_length=50, verbose_name='link')),
                ('sequence', models.IntegerField(verbose_name='order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodscategory', verbose_name='GoodsChannel Type')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodschannelgroup', verbose_name='GoodsChannel Name')),
            ],
            options={
                'verbose_name': 'GoodsChannel',
                'verbose_name_plural': 'GoodsChannel',
                'db_table': 'tb_goods_channel',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('caption', models.CharField(max_length=100, verbose_name='Subtitle')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Price')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Market Price')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('sales', models.IntegerField(default=0, verbose_name='Sales Volume')),
                ('comments', models.IntegerField(default=0, verbose_name='Number of Reviews')),
                ('is_launched', models.BooleanField(default=True, verbose_name='Available for Sale')),
                ('default_image', models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='', verbose_name='Default Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.goodscategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
                'db_table': 'tb_sku',
            },
        ),
        migrations.CreateModel(
            name='SKUImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'SKU Image',
                'verbose_name_plural': 'SKU Image',
                'db_table': 'tb_sku_image',
            },
        ),
        migrations.CreateModel(
            name='SPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('sales', models.IntegerField(default=0, verbose_name='Sales')),
                ('comments', models.IntegerField(default=0, verbose_name='Comments')),
                ('desc_detail', models.TextField(default='', verbose_name='Intro')),
                ('desc_pack', models.TextField(default='', verbose_name='Info')),
                ('desc_service', models.TextField(default='', verbose_name='Aftersale')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.brand', verbose_name='Brand')),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat1_spu', to='goods.goodscategory', verbose_name='First Class')),
                ('category2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat2_spu', to='goods.goodscategory', verbose_name='Second Class')),
                ('category3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat3_spu', to='goods.goodscategory', verbose_name='Third Class')),
            ],
            options={
                'verbose_name': 'SPU',
                'verbose_name_plural': 'SPU',
                'db_table': 'tb_spu',
            },
        ),
        migrations.AddField(
            model_name='sku',
            name='spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.spu', verbose_name='Product'),
        ),
        migrations.CreateModel(
            name='SPUSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('name', models.CharField(max_length=20, verbose_name='Specification Name')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='goods.spu', verbose_name='SPU')),
            ],
            options={
                'verbose_name': 'SPU Specification',
                'verbose_name_plural': 'SPU Specification',
                'db_table': 'tb_spu_specification',
            },
        ),
        migrations.CreateModel(
            name='SpecificationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('value', models.CharField(max_length=20, verbose_name='Option Value')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='goods.spuspecification', verbose_name='Specification')),
            ],
            options={
                'verbose_name': 'Specification Option',
                'verbose_name_plural': 'Specification Option',
                'db_table': 'tb_specification_option',
            },
        ),
        migrations.CreateModel(
            name='SKUSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='goods.sku', verbose_name='SKU')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.specificationoption', verbose_name='Specification Value')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.spuspecification', verbose_name='Specification Name')),
            ],
            options={
                'verbose_name': 'SKU Specification',
                'verbose_name_plural': 'SKU Specification',
                'db_table': 'tb_sku_specification',
            },
        ),
    ]
