# Generated by Django 6.0.5 on 2026-05-30 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsVisitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('count', models.IntegerField(default=0, verbose_name='count')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodscategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Visits',
                'verbose_name_plural': 'Visits',
                'db_table': 'tb_goods_visit',
            },
        ),
    ]
