# Generated by Django 6.0.5 on 2026-06-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_alter_oauthqquser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthqquser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
