# Generated by Django 6.0.5 on 2026-05-29 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('key', models.CharField(max_length=50, verbose_name='Category Key')),
            ],
            options={
                'verbose_name': 'Advertisement Content Category',
                'verbose_name_plural': 'Advertisement Content Category',
                'db_table': 'tb_content_category',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('url', models.CharField(max_length=300, verbose_name='Content URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('sequence', models.IntegerField(verbose_name='Display Order')),
                ('status', models.BooleanField(default=True, verbose_name='Display Status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contents.contentcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Advertisement Content',
                'verbose_name_plural': 'Advertisement Content',
                'db_table': 'tb_content',
            },
        ),
    ]
