# Generated by Django 6.0.5 on 2026-05-28 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('users', '0003_alter_user_options_user_email_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('title', models.CharField(max_length=20, verbose_name='Address Name')),
                ('receiver', models.CharField(max_length=20, verbose_name='Recipient')),
                ('place', models.CharField(max_length=50, verbose_name='Address')),
                ('mobile', models.CharField(max_length=11, verbose_name='Mobile Phone')),
                ('tel', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Landline Phone')),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Email')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Logical Deletion')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_addresses', to='areas.area', verbose_name='City')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district_addresses', to='areas.area', verbose_name='District')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province_addresses', to='areas.area', verbose_name='Province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Address',
                'db_table': 'tb_address',
                'ordering': ['-update_time'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='default_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.address', verbose_name='Default Address'),
        ),
    ]
