# Generated by Django 6.0.5 on 2026-06-01 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_goodsvisitcount'),
        ('users', '0006_alter_address_id_alter_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Order ID')),
                ('total_count', models.IntegerField(default=1, verbose_name='Total Quantity')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('freight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Shipping Fee')),
                ('pay_method', models.SmallIntegerField(choices=[(1, 'Cash on Delivery'), (2, 'Alipay')], default=1, verbose_name='Payment Method')),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending Payment'), (2, 'Pending Shipment'), (3, 'Pending Receipt'), (4, 'Pending Review'), (5, 'Completed'), (6, 'Cancelled')], default=1, verbose_name='Order Status')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.address', verbose_name='Shipping Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order Information',
                'verbose_name_plural': 'Order Information',
                'db_table': 'tb_order_info',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date Of Update')),
                ('count', models.IntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('comment', models.TextField(default='', verbose_name='Review')),
                ('score', models.SmallIntegerField(choices=[(0, '0 Points'), (1, '20 Points'), (2, '40 Points'), (3, '60 Points'), (4, '80 Points'), (5, '100 Points')], default=5, verbose_name='Satisfaction Score')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anonymous Review')),
                ('is_commented', models.BooleanField(default=False, verbose_name='Reviewed')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.sku', verbose_name='Product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='orders.orderinfo', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Item',
                'db_table': 'tb_order_goods',
            },
        ),
    ]
