[uwsgi]

http=127.0.0.1:8000
; socket=127.0.0.1:8001

chdir=/home/ccy/MEIDUO_MALL_PROJECT/meiduo_mall

module=meiduo_mall.wsgi:application

processes=4

threads=2

master=True

pidfile=uwsgi.pid

daemonize=uwsgi.log

virtualenv=/home/ccy/MEIDUO_MALL_PROJECT/.venv
